matrix:
  include:
    - os: linux
      sudo: required
      dist: jammy
      compiler: gcc
    - os: linux
      sudo: required
      dist: focal
      compiler: gcc
      env: DISTRIB_NAME=focal
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
      env: DISTRIB_NAME=bionic
    - os: osx
      osx_image: xcode14.2
      env: DISTRIB_NAME=macos

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
# g++ 10 specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install g++-10; fi
  - if [[ "$DISTRIB_NAME" == "focal" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9; fi
  - if [[ "$DISTRIB_NAME" == "focal" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 ; fi
  - if [[ "$DISTRIB_NAME" == "focal" ]]; then sudo update-alternatives --set gcc /usr/bin/gcc-10 ; fi
# End of g++ 10 specific part
#-----------------------
# CUDA specific part
#-----------------------
  - cuda_branch=1
  - echo $TRAVIS_BRANCH | grep -i cuda || cuda_branch=0
  - if [[ "$cuda_branch" == "0" ]]; then echo "non-CUDA branch"; else echo "CUDA branch"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then sudo apt-get install linux-headers-$(uname -r); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then distribution=$(. /etc/os-release;echo $ID$VERSION_ID | sed -e 's/\.//g'); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then wget https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/cuda-$distribution.pin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then sudo mv cuda-$distribution.pin /etc/apt/preferences.d/cuda-repository-pin-600; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/3bf863cc.pub; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then echo "deb https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then sudo apt-get -y install cuda-11-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" != "0" ]]; then PATH=/usr/local/cuda-11.7/bin/:$PATH ; fi
# End of CUDA specific part
#-----------------------
# SDL1.2 specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libsdl1.2-dev; fi
# End of SDL1.2 specific part
#-----------------------
# GLPK specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install glpk; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libglpk-dev; fi
# End of GLPK specific part
#-----------------------
# Microhttpd specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmicrohttpd; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmicrohttpd-dev; fi
# End of Microhttpd specific part
#-----------------------
  - MY_LOCATION=`pwd`
  - echo $MY_LOCATION
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories/edge_matching_puzzle
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - echo $MY_LOCATION
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - git clone https://github.com/quicky2000/EXT_microhttpd.git
  - git clone https://github.com/quicky2000/EXT_xmlParser.git
  - git clone https://github.com/quicky2000/FSM_base.git
  - git clone https://github.com/quicky2000/FSM_framework.git
  - git clone https://github.com/quicky2000/FSM_interfaces.git
  - git clone https://github.com/quicky2000/lib_bmp.git
  - git clone https://github.com/quicky2000/parameter_manager.git
  - git clone https://github.com/quicky2000/quicky_utils.git
  - git clone https://github.com/quicky2000/simple_gui.git
  - git clone https://github.com/quicky2000/combinatorics.git
  - git clone https://github.com/quicky2000/simplex.git
  - git clone https://github.com/quicky2000/EXT_glpk.git
  - git clone https://github.com/quicky2000/my_cuda.git
  - cd combinatorics
  - git checkout develop
  - cd $MY_LOCATION/repositories
  - cd quicky_tools/setup
  - . setup.sh
  - EXT_MICROHTTPD_INC_DIR=/usr/include
  - export EXT_MICROHTTPD_INC_DIR
  - EXT_MICROHTTPD_LIB_DIR=/usr/lib/x86_64-linux-gnu/
  - export EXT_MICROHTTPD_LIB_DIR
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
# quicky_tools do not support CUDA
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" == "0" ]]; then generate_makefile edge_matching_puzzle; make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" == "0" ]]; then run_test.py $MY_LOCATION/repositories/edge_matching_puzzle/tests; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd $MY_LOCATION ; mkdir cmake_build ; cd cmake_build ; fi
  - if [[ "$cuda_branch" == "0" ]]; then cmake $QUICKY_REPOSITORY/edge_matching_puzzle; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$cuda_branch" == "1" ]]; then sed -i 's/ENABLE_CUDA_CODE off/ENABLE_CUDA_CODE ON/' $QUICKY_REPOSITORY/edge_matching_puzzle/CMakeLists.txt; cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.7/bin/nvcc $QUICKY_REPOSITORY/edge_matching_puzzle; fi
  - make
# Cannot run tests in CUDA branch as there is no CUDA device on Travis
  - if [[ "$cuda_branch" == "0" ]]; then run_test.py $MY_LOCATION/repositories/edge_matching_puzzle/tests; fi
#EOF
